name: Codecov coverage report upload (Coordinator tests) for PRs from external forks

on:
  workflow_run:
    workflows: [coordinator-testing]
    types:
      - completed

jobs:
  upload-codecov-report:
    runs-on: ubuntu-latest
    name: upload-codecov-report
    steps:
      - name: HELLO
        run: |
          echo HELLO