name: Codecov coverage report upload (Coordinator tests) for PRs from external forks

on:
  workflow_run:
    workflows: [main]
    types:
      - completed

jobs:
  filter-commit-changes:
    runs-on: ubuntu-latest
    name: Filter commit changes
    outputs:
      coordinator: ${{ steps.filter.outputs.coordinator }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter commit changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          list-files: "json"
          filters: |
            coordinator:
              - '.github/**'

  upload-codecov-report:
    if: ${{ needs.filter-commit-changes.outputs.coordinator == 'true' }}
    runs-on: ubuntu-latest
    name: upload-codecov-report
    steps:
      - name: HELLO
        run: |
          echo HELLO