name: main

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  store-image-name-and-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to get full commit history
      - name: Get COMMIT_TAG
        shell: bash
        id: step1
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "COMMIT_TAG=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT
          else
            echo "COMMIT_TAG=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT
          fi
          # python ./.github/workflows/python-test.py
      - name: Show commit tag
        id: step2
        run: |
          echo "COMMIT_TAG: ${{ steps.step1.outputs.COMMIT_TAG }}"

      - name: Create empty .txt files
        run: |
          touch "a.txt"
          touch "b.txt"

      - name: Upload a.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: a-${{ steps.step1.outputs.COMMIT_TAG }}.txt
          path: ${{ github.workspace }}/a.txt

      - name: Upload b.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: b-${{ steps.step1.outputs.COMMIT_TAG }}.txt
          path: ${{ github.workspace }}/b.txt