name: Codecov coverage report upload (Coordinator tests) for PRs from external forkss

on:
  workflow_run:
    workflows: [main]
    types:
      - completed

jobs:
  filter-commit-changes:
    runs-on: ubuntu-latest
    name: Filter commit changes
    outputs:
      coordinator: ${{ steps.filter.outputs.coordinator }}
      smc: ${{ steps.filter.outputs.smc }}
      commit-tag: ${{ steps.get-commit-tag.outputs.COMMIT_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get commit tag
        shell: bash
        id: get-commit-tag
        run: |
          echo "COMMIT_TAG=$(git rev-parse --short ${{ github.event.workflow_run.head_sha }})" >> $GITHUB_OUTPUT
      - name: Show commit tag
        run: |
          echo "COMMIT_TAG: ${{ steps.get-commit-tag.outputs.COMMIT_TAG }}"
      - name: Filter commit changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          list-files: "json"
          filters: |
            coordinator:
              - '.github/**'
            smc:
              - '.github/**'

  upload-codecov-coordinator:
    needs: [ filter-commit-changes ]
    if: ${{ needs.filter-commit-changes.outputs.coordinator == 'true' }}
    runs-on: ubuntu-latest
    name: upload-codecov-report
    steps:
      - name: HELLO
        run: |
          echo ${{ needs.filter-commit-changes.outputs.commit-tag }}

  upload-codecov-smc:
    needs: [ filter-commit-changes ]
    if: ${{ needs.filter-commit-changes.outputs.smc == 'true' }}
    runs-on: ubuntu-latest
    name: upload-codecov-report
    steps:
      - name: HELLO
        run: |
          echo ${{ needs.filter-commit-changes.outputs.commit-tag }}