name: main

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coordinator-testing:
    uses: ./.github/workflows/coordinator-testing.yml
  smc-testing:
    uses: ./.github/workflows/run-smc-tests.yml
  python-test:
    uses: ./.github/workflows/run-python-test.yml