name: main

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  coordinator-testing:
    uses: ./.github/workflows/coordinator-testing.yml
  smc-testing:
    uses: ./.github/workflows/run-smc-tests.yml
  run-python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Run python test
        shell: bash
        run: |
          COMMIT_TAG=$(git rev-parse --short "$GITHUB_SHA")
          echo COMMIT_TAG
          # python ./.github/workflows/python-test.py