name: python-test

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Coordinator tests
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Run python test
        shell: bash
        run: python ${{ github.action_path }}/python-test.py