name: Smart contracts test

on:
  workflow_call:

jobs:
  run-contract-tests:
    runs-on: ubuntu-latest
    name: Run smart contracts tests
    steps:
      - name: HELLO
        run: |
          echo HELLOYELLO