name: python-test

on:
  workflow_call:

runs:
  using: "composite"
  runs-on: ubuntu-latest
  steps:
  - uses: actions/setup-python@v5
    with:
      python-version: '3.13'
      cache: 'pip'
  - name: Run python test
    shell: bash
    run: python ${{ github.action_path }}/python-test.py