name: Codecov coverage report upload for PRs from external forks

on:
  workflow_run:
    workflows: [main]
    types:
      - completed

permissions:
  actions: read
  contents: read # access to check out code and install dependencies

jobs:
  get-commit-tag:
    if: github.event.workflow_run.head_repository.fork == true
    runs-on: ubuntu-latest
    name: Get commit tag
    outputs:
      commit-tag: ${{ steps.get-commit-tag.outputs.COMMIT_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref:        ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0     # paths‑filter may need other commits
      - name: Get commit tag
        shell: bash
        id: get-commit-tag
        # COMMIT_TAG will be the commit SHA of the workflow run that triggered this workflow
        # - For a new commit on a PR branch, COMMIT_TAG = head of PR branch
        #
        # Note that we cannot use GITHUB_SHA here because it will always reference the head of main branch
        # Since we intend for this workflow to run only for PRs from an external fork, we want COMMIT_TAG to match the PR branch head
        run: |
          echo "COMMIT_TAG=$(git rev-parse --short ${{ github.event.workflow_run.head_sha }})" >> $GITHUB_OUTPUT
      - name: Show commit tag
        run: |
          echo "COMMIT_TAG: ${{ steps.get-commit-tag.outputs.COMMIT_TAG }}"
      - name: Debugging log
        run: |
          echo "1: ${{ github.event.workflow_run.id }}"
          echo "2: ${{ github.event.workflow_run.head_sha }}"
          echo "3: ${{ github.event.workflow_run.head_repository.full_name }}"

  upload-codecov-coordinator:
    needs: [ get-commit-tag ]
    runs-on: ubuntu-latest
    name: upload-codecov-coordinator
    steps:
      - name: Download a.txt
        uses: actions/download-artifact@v4
        with:
          name: a-${{ needs.get-commit-tag.outputs.commit-tag }}.txt
          path: |
            ${{ github.workspace }}/a-${{ needs.get-commit-tag.outputs.commit-tag }}.txt
          run-id: ${{ github.event.workflow_run.id }}

  upload-codecov-smart-contracts:
    needs: [ get-commit-tag ]
    runs-on: ubuntu-latest
    name: upload-codecov-smart-contracts
    steps:
      - name: Download a.txt
        uses: actions/download-artifact@v4
        with:
          name: a-${{ needs.get-commit-tag.outputs.commit-tag }}.txt
          path: |
            ${{ github.workspace }}/a-${{ needs.get-commit-tag.outputs.commit-tag }}.txt
          run-id: ${{ github.event.workflow_run.id }}

